#include "gpio.h"

void init_gpio(void)
{
    GPIO_SET_OUTPUT(LCD_1602_PD0);
    GPIO_SET_OUTPUT(LCD_1602_PD1);
    GPIO_SET_OUTPUT(LCD_1602_PD2);
    GPIO_SET_OUTPUT(LCD_1602_PD3);
    GPIO_SET_OUTPUT(LCD_1602_PD4);
    GPIO_SET_OUTPUT(LCD_1602_PD5);
    GPIO_SET_OUTPUT(LCD_1602_PD6);
    GPIO_SET_OUTPUT(LCD_1602_PD7);
    GPIO_SET_OUTPUT(LCD_1602_RS);
    GPIO_SET_OUTPUT(LCD_1602_E);
	
    GPIO_SET_OUTPUT(BUZZER);
	
    GPIO_SET_OUTPUT(LED);
	
    GPIO_SET_INPUT(BUTTON);
    GPIO_HIGH(BUTTON); // pull up internal resistor
	
    GPIO_SET_INPUT(SCORE_RESET);
    GPIO_HIGH(SCORE_RESET); // pull up internal resistor
}