#ifndef IR_SENSORS_H_
#define IR_SENSORS_H_

#define TOP_LEFT_SENSOR_ONCOMING_EVENT_MASK         0x80
#define TOP_LEFT_SENSOR_DISTANCING_EVENT_MASK       0x40
#define TOP_RIGHT_SENSOR_ONCOMING_EVENT_MASK        0x20
#define TOP_RIGHT_SENSOR_DISTANCING_EVENT_MASK      0x10
#define BOTTOM_LEFT_SENSOR_ONCOMING_EVENT_MASK      0x08
#define BOTTOM_LEFT_SENSOR_DISTANCING_EVENT_MASK    0x04
#define BOTTOM_RIGHT_SENSOR_ONCOMING_EVENT_MASK     0x02
#define BOTTOM_RIGHT_SENSOR_DISTANCING_EVENT_MASK   0x01

#include <stdbool.h>

extern int8_t events_mask;

void ir_sensors_poll(void);

#endif /* IR_SENSORS_H_ */